export { default as yieldOrContinue } from './src/yieldOrContinue'
export { default as yieldControl } from './src/yieldControl'
export { default as isTimeToYield } from './src/isTimeToYield'
export { default as scheduleTask } from './src/scheduleTask'
export type { default as SchedulingStrategy } from './src/SchedulingStrategy'
